version: 2
jobs:
  buildlinux:
    docker:
      - image: ubuntu:trusty
    steps:
      - checkout
      - run:
          name: Build
          command: sh ci/linux.sh build
      - run:
          name: Build Android
          command: BUILD_ANDROID=1 sh ci/linux.sh build
  buildmac:
    macos:
      xcode: "9.0"
    steps:
      - run:
          name: Build OSX
          command: xcodebuild -version

workflows:
  version: 2
  build:
    jobs:
      - buildlinux
      - buildmac
